PARAMETER_CATALOG = [
    {
        "tag": "ViewFromWindows",
        "name": "Вид из окон",
        "kind": "multi",
        "values": ["Во двор", "На улицу", "На солнечную сторону"],
        "supported": True,
    },
    {
        "tag": "PassengerElevator",
        "name": "Пассажирские лифты",
        "kind": "select",
        "values": [str(value) for value in range(1, 9)],
        "supported": True,
    },
    {
        "tag": "FreightElevator",
        "name": "Грузовые лифты",
        "kind": "select",
        "values": [str(value) for value in range(1, 9)],
        "supported": True,
    },
    {
        "tag": "BathroomMulti",
        "name": "Санузел",
        "kind": "multi",
        "values": ["Раздельный", "Совмещенный"],
        "supported": True,
    },
    {
        "tag": "CeilingHeight",
        "name": "Высота потолков",
        "kind": "number",
        "min": 2,
        "max": 10,
        "step": 0.01,
        "supported": True,
    },
    {
        "tag": "Courtyard",
        "name": "Двор",
        "kind": "multi",
        "values": ["Закрытая территория", "Детская площадка", "Спортивная площадка"],
        "supported": True,
    },
    {
        "tag": "Parking",
        "name": "Парковка",
        "kind": "multi",
        "values": [
            "Подземная",
            "Наземная многоуровневая",
            "Открытая во дворе",
            "За шлагбаумом во дворе",
            "Гостевая",
        ],
        "supported": True,
    },
    {
        "tag": "NDAdditionally",
        "name": "Дополнительно о новостройке",
        "kind": "multi",
        "values": ["Гардеробная", "Панорамные окна"],
        "supported": True,
    },
]
